# Generated by Django 2.0.2 on 2018-04-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20180414_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='home',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
