# Generated by Django 2.0.2 on 2018-04-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20180414_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='value',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
