# Generated by Django 2.0.4 on 2018-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20180415_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='room',
            name='home_amount',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='room',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
